version: '2'
services:
    proxy:
        image: ehazlett/docker-proxy:latest
        container_name: "hostproxy"
        command: -i
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        expose:
            - "2375"
        ports:
            - "2375:2375"


    caddy:
        build: 
           context: ./caddy
           dockerfile: Dockerfile
        container_name: "caddy"
        ports: 
           - "80:80"
           - "443:443"
        volumes:
           - "./application/:/srv"
           - "./application/CaddyFile:/etc/Caddyfile"
        depends_on:
            - proxy
        links:
            - proxy